---

- name: Get CVE Fix
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Debug Hostvars
      ansible.builtin.debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      ansible.builtin.set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      ansible.builtin.debug:
        var: payload


    - name: Set fact CVE {{ payload.events[0].payload.reported_cve }} Name
      ansible.builtin.set_stats:
        data:
          cve_name: "{{ payload.events[0].payload.reported_cve }}"

    - name: Debug CVE {{ payload.events[0].payload.reported_cve }} Name
      ansible.builtin.debug:
        msg: "CVE Name: {{ payload.events[0].payload.reported_cve }}"

    # - name: Check whether there is a Fix available on Lightspeed
    #   ansible.builtin.assert:
    #     that:
    #       - affected_systems > 0
    #     fail_msg: "There is no Fix available on Lightspeed, moving to AI-based Mitigation"
    #     success_msg: "There is a Fix available on Lightspeed, moving to Patching"

    - name: Get access token using Service Account Client ID and Secret
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: "form-urlencoded"
        body:
          grant_type: client_credentials
          client_id: "{{ lightspeed_client_id }}"
          client_secret: "{{ lightspeed_client_secret }}"
        status_code: 200
      register: sso_response

    - name: Query Lightspeed for CVE {{ payload.events[0].payload.reported_cve }}
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ payload.events[0].payload.reported_cve }}"
        method: GET
        headers:
          Authorization: "Bearer {{ sso_response.json.access_token }}"
        status_code: 200
      register: cve_response

    - name: Generate Remediation Playbook for the CVE
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/remediations/v1/remediations"
        method: POST
        force_basic_auth: yes
        url_username: "{{ insights_username }}"
        url_password: "{{ insights_password }}"
        body_format: json
        body:
          name: "Remediation for {{ target_cve }}"
          add:
            issues:
              - id: "vulnerabilities:{{ target_cve }}"
            # Supply the Insights System IDs (inventory IDs) you want to patch
            systems: "{{ affected_system_uuid_list }}" 
        status_code: 201
      register: remediation_job
      
    - name: Download the generated Remediation Playbook (.yml)
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/remediations/v1/remediations/{{ remediation_job.json.id }}/playbook"
        method: GET
        force_basic_auth: yes
        url_username: "{{ insights_username }}"
        url_password: "{{ insights_password }}"
        dest: "/tmp/insights_patch_remediation.yml"
        status_code: 200
