---

- name: Get AI generated Mitigation Code
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Fetch CVE data from Red Hat Security Data API
      ansible.builtin.uri:
        url: "https://access.redhat.com/hydra/rest/securitydata/cve/{{ cve_name }}.json"
        method: GET
        return_content: true
        status_code: 200
      register: cve_response

    - name: Display CVE details
      ansible.builtin.debug:
        var: cve_response.json

    - name: Set the CVE Details
      ansible.builtin.set_fact:
        cve_details: "{{ cve_response.json.details | default('No details available for this CVE.') }}"

    - name: Display CVE Mitigation
      ansible.builtin.set_fact:
        cve_mitigation: "{{ cve_response.json.mitigation.value | default('No mitigation available for this CVE.') }}"

    - name: Display CVE References
      ansible.builtin.set_fact:
        cve_references: "{{ cve_response.json.references | default('No mitigation available for this CVE.') }}"

    - name: Set fact prompt
      ansible.builtin.set_fact:
        prompt: >
                Write an ansible playbook to mitigate {{ cve_name }}.
                The playbbok MUST only cover RHEL as the OS for target nodes.
                I DON'T want you to update any package or kernel binary,
                I just want to do mitogation playing with kernel parameters
                and similar mitigation measures.
                The CVE has the following details, mitigation and references:
                Details: '{{ cve_details }}'.
                Mitigation: '{{ cve_mitigation }}'.
                References: '{{ cve_references }}'.
                You MUST use the following string as ansible play targets (hosts): 
                '{{ affected_systems_fqdn | join(',') }}'.

# Write an ansible playbook to mitigate CVE {{ cve_name }}.
# You MUST use the following string as ansible play targets (hosts): 
# '{{ affected_systems_fqdn | join(',') }}'.
# You MUST NOT use block structures on handlers.
# I DON'T want to update any package or kernel, only do mitigation.
# If kernel update is needed, update for latest, not specific one.
# Do NOT add inline comments jinja2 or JSON code!
# Do NOT ensure the latest kernel package is installed!
# The CVE has the following details, mitigation and references:
# Details: '{{ cve_details }}'.
# Mitigation: '{{ cve_mitigation }}'.
# References: '{{ cve_references }}'.

    - name: Prompt Openshift AI
      ansible.builtin.uri:
        url: "{{ ai_endpoint }}"
        method: POST
        body:
          model: "{{ ai_model }}"
          messages: 
            - content: "{{ prompt }}"
        status_code: 200
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ai_token }}"
        validate_certs: yes
      register: ai_response
      retries: 10
      delay: 5
      until: ai_response.status == 200

    - name: Debug Prompt to Openshift AI
      debug:
        var: ai_response

    - name: Set Generated Ansible Playbook
      ansible.builtin.set_fact:
        generated_playbook: >-
          {{ ai_response.json.choices[0].message.reasoning_content |
          wordwrap(60) |
          comment('plain', prefix='####### REASONING #######', postfix='#######') }}
          
          {{ ai_response.json.choices[0].message.content
             .split('```yaml')[1].split('```')[0] | trim }}

    - name: Debug generated Playbook
      ansible.builtin.debug:
        var: generated_playbook

    - name: Set stats generated Playbook
      ansible.builtin.set_stats:
        data:
          generated_playbook: "{{ generated_playbook }}"

