---

- name: Check CVE Details
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    # - name: Debug Hostvars
    #   ansible.builtin.debug:
    #     var: hostvars['localhost']

    # - name: AIOps Lightspeed action payload
    #   ansible.builtin.set_fact:
    #     payload: "{{ ansible_eda.event.payload }}"

    # - name: Debug Payload
    #   ansible.builtin.debug:
    #     var: payload

    # - name: Set fact {{ payload.events[0].payload.reported_cve }} Name
    #   ansible.builtin.set_fact:
    #     cve_name: "{{ payload.events[0].payload.reported_cve }}"

    # - name: Set stats {{ cve_name }} Name
    #   ansible.builtin.set_stats:
    #     data:
    #       cve_name: "{{ cve_name }}"

    # - name: Debug {{ cve_name }} Name
    #   ansible.builtin.debug:
    #     msg: "CVE Name: {{ cve_name }}"

    # - name: Get access token using Service Account Client ID and Secret
    #   ansible.builtin.uri:
    #     url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    #     method: POST
    #     body_format: "form-urlencoded"
    #     body:
    #       grant_type: client_credentials
    #       client_id: "{{ lightspeed_client_id }}"
    #       client_secret: "{{ lightspeed_client_secret }}"
    #     status_code: 200
    #   register: sso_response

    # - name: Query Lightspeed for the affected systems
    #   ansible.builtin.uri:
    #     url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ cve_name }}/affected_systems"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ sso_response.json.access_token }}"
    #     status_code: 200
    #   register: affected_systems_response
    #   ignore_errors: true

    # - name: Set fact Affected Systems
    #   ansible.builtin.set_fact:
    #     affected_systems: "{{ affected_systems_response.json.data | map(attribute='id') | list }}"

    # - name: Set stats Affected Systems
    #   ansible.builtin.set_stats:
    #     data:
    #       affected_systems: "{{ affected_systems }}"

    # - name: Debug Affected Systems
    #   ansible.builtin.debug:
    #     msg: "Affected Systems: {{ affected_systems }}"

    # - name: Exit cleanly if this is not the staging path
    #   ansible.builtin.meta: end_play
    #   when: affected_systems | length == 0

    # - name: Check whether any System is Affected
    #   ansible.builtin.assert:
    #     that:
    #       - affected_systems | length > 0
    #     fail_msg: "There ARE NO Systems affected by {{ cve_name }}"
    #     success_msg: "There ARE Systems affected by {{ cve_name }}: {{ affected_systems }}"

    - name: Get access token using Service Account Client ID and Secret
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: "form-urlencoded"
        body:
          grant_type: client_credentials
          client_id: "{{ lightspeed_client_id }}"
          client_secret: "{{ lightspeed_client_secret }}"
        status_code: 200
      register: sso_response

    - name: Query Lightspeed for {{ payload.events[0].payload.reported_cve }}
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ payload.events[0].payload.reported_cve }}"
        method: GET
        headers:
          Authorization: "Bearer {{ sso_response.json.access_token }}"
        status_code: 200
      register: cve_response

    - name: Debug CVE Response
      ansible.builtin.debug:
        var: cve_response    

    - name: Debug {{ payload.events[0].payload.reported_cve }} Description
      ansible.builtin.debug:
        msg: "CVE Description: {{ cve_response.json.data.attributes.description }}"

    - name: Set fact {{ payload.events[0].payload.reported_cve }} Description
      ansible.builtin.set_fact:
        cve_description: "{{ cve_response.json.data.attributes.description }}"

    - name: Set stats {{ payload.events[0].payload.reported_cve }} Description
      ansible.builtin.set_stats:
        data:
          cve_description: "{{ cve_response.json.data.attributes.description }}"

    - name: Check whether there are Fixes available on Lightspeed for 
      ansible.builtin.assert:
        that:
            #- cve_response.json.data.attributes.advisories_list | length == 0
            - cve_response.json.data.attributes.advisories_list | length > 0
        fail_msg: "There ARE NO Advisories (Fixes) available on Lightspeed. Going to use AI-based Mitigation"
        success_msg: "There ARE Advisories (Fixes) available on Lightspeed: {{ cve_response.json.data.attributes.advisories_list }}. Going to apply Patching."
