---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: RHELs with Lightspeed Action
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['rhel'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    - name: Debug Hostvars
      debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      debug:
        var: payload

    # {
    #   "bundle": "rhel",
    #   "application": "vulnerability",
    #   "version": "v1.1.0",
    #   "event_type": "any-cve-known-exploit",
    #   "timestamp": "2025-03-19T20:19:19.958529",
    #   "context": {
    #     "display_name": "randomserver",
    #     "inventory_id": "704fe5b0-210d-47d5-9483-e8dab3348432",
    #     "org_id": "13959588"
    #   },
    #   "events": [
    #     {
    #       "metadata": {},
    #       "payload": {
    #         "reported_cve": "CVE-2025-24201",
    #         "cvss_score": 7.5,
    #         "impact_id": 5,
    #         "known_exploit": true,
    #         "has_rule": false,
    #         "publish_date": "2025-03-11T00:00:00+00:00"
    #       }
    #     }
    #   ],
    #   "recipients": [
    #     {
    #       "only_admins": false,
    #       "ignore_user_preferences": false
    #     }
    #   ],
    #   "org_id": "13959588"
    # }

  ######
  # GET CVE description
  ######

    - name: Authenticate using Service Account Client ID and Secret
      uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: "form-urlencoded"
        body:
          grant_type: client_credentials
          client_id: "{{ lightspeed_client_id }}"
          client_secret: "{{ lightspeed_client_secret }}"
        status_code: 200
      register: sso_response
      no_log: false # Protects the resulting access token from appearing in logs

    - name: Fetch CVE data from Red Hat Insights Vulnerability API
      uri:
        url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ payload.events[0].payload.reported_cve }}"
        method: GET
        headers:
          Authorization: "Bearer {{ sso_response.json.access_token }}"
          Accept: "application/json"
        status_code: 200
      register: cve_response


  ######
  # AI Prompt
  ######

    - name: Prompt to Openshift AI
      ansible.builtin.uri:
        url: "{{ ai_endpoint }}"
        method: POST
        body: |
          { 
          "model": "{{ ai_model }}",
          "prompt": "Give me an example of a basic ansible playbook",
          "max_tokens": {{ ai_max_tokens }},
          "temperature": 0
          }
        status_code: 200
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ai_token }}"
        validate_certs: yes
      delegate_to: localhost
      register: ai_response

    - name: Debug Prompt to Openshift AI
      debug:
        var: ai_response

    - name: Extract clean Ansible Playbook
      ansible.builtin.set_fact:
        clean_playbook: >-
          {{
            (ai_response.json.choices[0].text | 
            regex_search('```yaml\n([\s\S]*?)\n```', '\1'))[0]
          }}

    - name: Debug Clean Playbook
      debug:
        var: clean_playbook

    # curl -X POST https://maas-rhdp.apps.maas.redhatworkshops.io/v1/completions \
    #   -H "Content-Type: application/json" \
    #   -H "Authorization: Bearer sk-fgFlaBkDridZSPUNWiIjZA" \
    #   -d '{
    #     "model": "openai/granite-3-2-8b-instruct",
    #     "prompt": "What is the capital of USA?",
    #     "max_tokens": 100,
    #     "temperature": 0
    #   }' | jq -r '.choices[0].text'

    ######
    # Store playbook on GIT
    ######
    - name: Retrieve a repository
      ansible.scm.git_retrieve:
        origin:
          url: "{{ github_url }}"
        upstream:
          url: "{{ github_url }}"
        branch: 
          name: "{{ github_branch }}"
          duplicate_detection: false
      register: repository

    - name: Debug repository data
      debug: 
        var: repository

    - name: Copy playbook content to the GIT folder
      ansible.builtin.copy:
        content: "{{ clean_playbook }}"
        dest: "{{ repository['path'] }}/playbook_fix_{{ payload.events[0].payload.reported_cve }}.yml"
        force: true
        mode: '0644'

    - name: Publish the changes
      ansible.scm.git_publish:
        commit:
          message: Adding new playbook_fix_{{ payload.events[0].payload.reported_cve }}.yml"
        path: "{{ repository['path'] }}"
        user:
          name: "{{ github_user }}"
          email: "{{ github_email }}"
        token: "{{ github_token }}"

    ######
    # Create Job Template and Project
    ######
    - name: Create Project and Job Template
      vars:
        aap_hostname: "https://{{ aap_fqdn }}"
        aap_username: admin
        aap_password: "{{ admin_password }}"
        aap_validate_certs: false
        controller_projects:
          - name: "AWS AIOps Fix Project"
            description: "AWS AIOps Fix Project"
            organization: "Default"
            scm_type: "git"
            scm_url: "{{ github_url }}"
            scm_update_on_launch: "True"
            execution_environment: "{{ ee_name }}"
            wait: true            
        controller_templates:
          - name: "AWS AIOps: X. Fix CVE {{ payload.events[0].payload.reported_cve }}"
            description: ""
            organization: "Default"
            project: "AWS AIOps Fix Project"
            inventory: "AWS Inventory"
            playbook: "playbook_fix_{{ payload.events[0].payload.reported_cve }}.yml"
            verbosity: 0
            #job_type: "check"
            job_type: "run"
            credentials:
              - "AWS Credential"
              - "AWS AIOps Ansible Credential"
            execution_environment: "{{ ee_name }}"
            survey_enabled: false
        dispatch_include_wildcard_vars: true
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch        
      # ansible.builtin.include_role:
      #   name: "{{ item }}"
      # loop:  
      #   - infra.aap_configuration.controller_projects
      #   - infra.aap_configuration.controller_project_update
      #   - infra.aap_configuration.controller_job_templates
