---

- name: Check CVE Details
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Debug Hostvars
      ansible.builtin.debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      ansible.builtin.set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Events
      ansible.builtin.debug:
        var: payload

    - name: Loop over all CVEs
      debug:
        var: "{{ item }}"
      loop: "{{ payload.events }}"


    
# ansible_facts:
#   payload:
#     account_id: null
#     application: vulnerability
#     bundle: rhel
#     context:
#       display_name: ec2-54-237-246-170.compute-1.amazonaws.com
#       inventory_id: 06eb0ac2-ac4d-4bd4-8b66-ca8fc9744793
#       org_id: '15801425'
#     event_type: system-cve-known-exploit
#     events:
#       - metadata: {}
#         payload:
#           cvss_score: 7.8
#           has_rule: false
#           impact_id: 5
#           known_exploit: true
#           publish_date: '2025-07-22T00:00:00+00:00'
#           reported_cve: CVE-2025-38352
#       - metadata: {}
#         payload:
#           cvss_score: 7.8
#           has_rule: false
#           impact_id: 5
#           known_exploit: true
#           publish_date: '2026-04-22T00:00:00+00:00'
#           reported_cve: CVE-2026-31431
#     org_id: '15801425'
#     severity: CRITICAL
#     source:
#       application:
#         display_name: Vulnerability
#       bundle:
#         display_name: Red Hat Enterprise Linux
#       event_type:
#         display_name: System vulnerability with known exploit
#     timestamp: '2026-07-29T12:57:15.571532'
# _ansible_no_log: false
# changed: false    