---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: RHELs with Lightspeed Action
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:

    - name: Set provider
      set_fact: 
        panos_provider: 
          ip_address: "{{ groups['rhel'][0] }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"

    - name: Debug Hostvars
      debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      debug:
        var: payload

    # {
    #   "bundle": "rhel",
    #   "application": "vulnerability",
    #   "version": "v1.1.0",
    #   "event_type": "any-cve-known-exploit",
    #   "timestamp": "2025-03-19T20:19:19.958529",
    #   "context": {
    #     "display_name": "randomserver",
    #     "inventory_id": "704fe5b0-210d-47d5-9483-e8dab3348432",
    #     "org_id": "13959588"
    #   },
    #   "events": [
    #     {
    #       "metadata": {},
    #       "payload": {
    #         "reported_cve": "CVE-2025-24201",
    #         "cvss_score": 7.5,
    #         "impact_id": 5,
    #         "known_exploit": true,
    #         "has_rule": false,
    #         "publish_date": "2025-03-11T00:00:00+00:00"
    #       }
    #     }
    #   ],
    #   "recipients": [
    #     {
    #       "only_admins": false,
    #       "ignore_user_preferences": false
    #     }
    #   ],
    #   "org_id": "13959588"
    # }


    - name: Prompt to Openshift AI
      ansible.builtin.uri:
        url: "{{ ai_endpoint }}"
        method: POST
        body: |
          { 
          "model": "{{ ai_model }}",
          "prompt": "What is the capital of USA?",
          "max_tokens": {{ ai_max_tokens }},
          "temperature": 0
          }
        status_code: 201
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ai_token }}"
        validate_certs: yes
      delegate_to: localhost
      register: ai_response

    - name: Debug Prompt to Openshift AI
      debug:
        var: ai_response

    # curl -X POST https://maas-rhdp.apps.maas.redhatworkshops.io/v1/completions \
    #   -H "Content-Type: application/json" \
    #   -H "Authorization: Bearer sk-fgFlaBkDridZSPUNWiIjZA" \
    #   -d '{
    #     "model": "openai/granite-3-2-8b-instruct",
    #     "prompt": "What is the capital of USA?",
    #     "max_tokens": 100,
    #     "temperature": 0
    #   }' | jq -r '.choices[0].text'