---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: RHELs with Lightspeed Action
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Debug Hostvars
      debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      debug:
        var: payload


  ######
  # AI Prompt
  ######

    # - name: Prompt Openshift AI
    #   vars:
    #     prompt: >
    #             Write an ansible playbook to mitigate the following CVE:
    #             '{{ cve_description }}'
    #             Return for me only the playbook code, remove all other text.
    #   ansible.builtin.uri:
    #     url: "{{ ai_endpoint }}"
    #     method: POST
    #     body:
    #       model: "{{ ai_model }}"
    #       prompt: "{{ prompt }}"
    #       max_tokens: "{{ ai_max_tokens }}"
    #       temperature: 0
    #     status_code: 200
    #     body_format: json
    #     headers:
    #       Content-Type: "application/json"
    #       Authorization: "Bearer {{ ai_token }}"
    #     validate_certs: yes
    #   delegate_to: localhost
    #   register: ai_response

    # - name: Debug Prompt to Openshift AI
    #   debug:
    #     var: ai_response

    # - name: Set Generated Ansible Playbook
    #   ansible.builtin.set_fact:
    #     generated_playbook: >-
    #       {{ ai_response.json.choices[0].text
    #          .split('```yaml')[1]
    #          .split('```')[0]
    #          | trim }}

    - name: Prompt Openshift AI
      vars:
        prompt: >
                Write an ansible playbook to mitigate the following CVE:
                '{{ cve_description }}'
                Return for me only the playbook code, remove all other text.
      ansible.builtin.uri:
        url: "{{ ai_endpoint }}"
        method: POST
        body:
          model: "{{ ai_model }}"
          messages: 
            - content: "{{ prompt }}"
          #max_tokens: "{{ ai_max_tokens }}"
        status_code: 200
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ai_token }}"
        validate_certs: yes
      delegate_to: localhost
      register: ai_response

    - name: Debug Prompt to Openshift AI
      debug:
        var: ai_response

    - name: Set Generated Ansible Playbook
      ansible.builtin.set_fact:
        generated_playbook: >-
          {{ ai_response.json.choices[0].message.reasoning_content |
          comment('plain', prefix='#######\n#', postfix='#\n#######\n') }}" }}
          + 
          {{ ai_response.json.choices[0].message.content
             .split('```yaml')[1]
             .split('```')[0]
             | trim }}

    - name: Debug Clean Playbook
      debug:
        var: generated_playbook


    ######
    # Store playbook on GIT
    ######

    - name: Retrieve a repository
      ansible.scm.git_retrieve:
        origin:
          url: "{{ github_url }}"
        upstream:
          url: "{{ github_url }}"
        branch: 
          name: "{{ github_branch }}"
          duplicate_detection: false
      register: repository

    - name: Debug repository data
      debug: 
        var: repository

    - name: Copy playbook content to the GIT folder
      ansible.builtin.copy:
        content: "{{ generated_playbook }}"
        dest: "{{ repository['path'] }}/playbook_mitigation.yml"
        force: true
        mode: '0644'

    - name: Publish the changes
      ansible.scm.git_publish:
        commit:
          message: Adding new playbook_fix_{{ cve_name }}.yml"
        path: "{{ repository['path'] }}"
        user:
          name: "{{ github_user }}"
          email: "{{ github_email }}"
        token: "{{ github_token }}"

