---

# example_rulebook.yaml
- name: Red Hat Insights (Lightspeed)
  hosts: localhost
  sources:
    # console.redhat.com -> Settings -> Integrations -> Reporting & automation -> Event-Driven Ansible
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 10000
        # token:    # secret token.
        # certfile: # (optional) path to a certificate file to enable TLS support
        # keyfile:  # (optional) path to a key file to be used together with certfile
        # password: # (optional) path to a key file to be used together with certfile
  rules:
    - name: Always true
      condition:
        event.payload is defined
      actions:
        - print_event:
            pretty: true
        - run_job_template:
            organization: "Default"
            name: "AWS AIOps: X. Action"
            labels:
              - EDA Lightspeed

    - name: Match Advisor Recommendation Event
      condition:
        event.payload.application == "advisor"
        and event.payload.event_type == "new-recommendation"
        # event.payload.application == "malware-detection"
        # and event.payload.event_type == "detected-malware"
      actions:
        - print_event:
            pretty: true
        - run_job_template:
            organization: "Default"
            name: "AWS AIOps: X. Action"
            labels:
              - EDA Lightspeed

    - name: match vulnerability event
      condition: |-
        event.payload.application == "vulnerability"
        and event.payload.event_type in [
          "new-recommendation",
          "any-cve-known-exploit",
          "new-cve-cvss",
          "new-cve-severity",
          "new-cve-security-rule"
        ]
      actions:
        - print_event:
            pretty: true
        # - run_job_template:
        #     organization: "Default"
        #     name: "AIOps: XXX"
        # labels:
        #   - EDA Lightspeed

    - name: Match Compliance Below Threshold
      condition:
        event.payload.application == "compliance"
        and event.payload.event_type == "compliance-below-threshold"
      actions:
        - print_event:
            pretty: true
        # - run_job_template:
        #     organization: "Default"
        #     name: "AIOps: XXX"
        # labels:
        #   - EDA Lightspeed
